# Base configuration
permalink: http://www.graybrooks.com
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]
markdown: kramdown
pygments: true

#Prose.io editing info
repo_name: gbinal.github.com
branch: master
#GitHub organization name *or* username
gh_org: gbinal.github.com
prose_url: http://prose.io
site_url: http://www.graybrooks.com
media: assets/img


# Your Programs's Name
name: Gray Brooks
subtitle: Ever forward...

# When using this template with a project page set the baseurl to '/project-name'
# For user/organization pages set this to an empty string
# When working locally use jekyll serve --baseurl '' so that you can view everything at localhost:4000
# See http://jekyllrb.com/docs/github-pages/ for more info
#baseurl: ''
baseurl: 'http://www.graybrooks.com'

# Author/Organization info to be displayed in the templates
author:
  name: Gray Brooks
  url: http://www.graybrooks.com

# ------------------------------------------------------------------
#   Navigation
#   List links that should appear in the site sidebar here
#   "pages" is a directory to keep web content that are not posts
# ------------------------------------------------------------------
navigation:
- text: Home
  url: /index.html
  internal: true
- text: APIs In Government
  url: http://pages.18f.gov/API-All-the-X/
  internal: true
- text: Good Stuff
  url: /pages/good_stuff
  internal: true
  text: 2016 Election
  url: /2016-election/
  internal: true
- text: GitHub
  url: https://github.com/gbinal
  internal: true
- text: Suggest An Edit
  url: https://github.com/gbinal/gbinal.github.com/issues
  internal: true
